version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy      # espera que postgres esté listo
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Admin123
      - DB_NAME=proyecto_seguridad
      - DB_PORT=5432
      - JWT_SECRET=KJH78sd9f7sdf98sdf7sdf98sdf7sdf98sdf
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: proyecto_seguridad
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proyecto_seguridad"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: